### ISSUE TITLE
sgminer not loading

### ISSUE THREAD

**Issue by petrosch** [djm34/sgminer-msvc2015#10]
Hi, 
I am creating a batch file with this entry
sgminer.exe -a lyra2z -o stratum+tcp://POOLADDRESS:PORT -u username -p password

When I execute the command prompt screen of sgminer appears for a split of a second and then closes down. I have an AMD Radeon FX 7500 card
Any ideas?
Thanks

**Comment by djm34** [comment]
you probably have a typo somewhere... here my command line
sgminer    --kernel lyra2Z   -o  stratum+tcp://dash80.suprnova.cc:80 -u djm34.1 -p password  -I 18

yeah try --kernel instead of -a

**Comment by djm34** [comment]
maybe try to add --worksize 32 to the command line

**Comment by petrosch** [comment]
Thank you very much, i will give it a try and let you kniw

**Comment by petrosch** [comment]
Hello, I tried to use --kernel instead of -a, along with the other options you suggested, this time the command prompt screen does not close down, but I get the error message shown on the attached pic...
![sgmin](https://user-images.githubusercontent.com/29517335/27494876-12307606-5850-11e7-95a6-ab4e238b1070.jpg)

What am I doing wrong?

**Comment by djm34** [comment]
you are probably using the wrong gpu platform. 
But please quote in your message the full command line you are using otherwise I can't understand (beside best guess) what could be wrong.

**Comment by petrosch** [comment]
Thanks
I tried again and this time I left it open, then I got this> it looks like it is mining, but I am not sure if it is working right since it was showing the error message before.
This is the command line I used
sgminer.exe --kernel lyra2z --worksize 32 -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:20581 -u petrosc.12 -p password -I 12
It also seems to work without the worksize 32 command
![sgmin](https://user-images.githubusercontent.com/29517335/27508518-2e757db0-58e7-11e7-8540-b0adac7ad441.jpg)

**Comment by djm34** [comment]
ok good to know it works
