### ISSUE TITLE
Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)

### ISSUE THREAD

**Issue by mosincos** [djm34/sgminer-msvc2015#11]
Hi,
I use sgminer to mine Zcoin(XZC), when I start .bat, it shows error:"Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)", My card: AMD RX580 8G (Windows 10), Could you tell me how to fix that? thank you.

![screenshot20170619115523](https://user-images.githubusercontent.com/11146532/27270322-db1b40aa-54ef-11e7-99c7-794d18e5dfbd.png)

**Comment by mosincos** [comment]
windows 10

**Comment by djm34** [comment]
it doesn't really help if you don't give the command line you used. 
However it is probably due to the fact you used a worksize larger than 32 (the default is larger), so you need to add --worksize 32 to the command line in your bat file

**Comment by mosincos** [comment]
Thank you it work! :D
