### ISSUE TITLE
cannot specify device

### ISSUE THREAD

**Issue by 2W0** [djm34/sgminer-msvc2015#12]
When i run my BAT file i get an error saying the device specified does not exist, followed by an immediate closing of the miner. 

sgminer.exe -k lyra2z -o stratum+tcp://asia.lyra2z-hub.miningpoolhub.com:20581 -u me.workerme -p x --auto-fan --auto-gpu --temp-target 80 -d 1

I have a GTX 970 and an RX 480.  If i do not specify a device in the command line, it tries to run with the NVIDIA and obviously does not work correctly.  If i do specify the AMD(d 1) it says the device does not exist.  

Any help?

**Comment by djm34** [comment]
You have to precise the platform --gpu-platform 1 (most likely if it fails) meaning the nvidia cards are on gpu--platform 0 and the amd cards on --gpu-platform 1 (or eventually 2)
