### ISSUE TITLE
Build on Ubuntu Xenial

### ISSUE THREAD

**Issue by fabstao** [djm34/sgminer-msvc2015#17]
Hi!

I cloned git and ran:

`
git submodule init
git submodule update
autoreconf -i`

And got the following error:

`autoreconf -i
configure.ac:12: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1`

How should I build for Ubuntu Xenial? Is it supported? Thanks

**Comment by fabstao** [comment]
I didnt run the commands in the correct order, now is working :)

**Comment by djm34** [comment]
ok great :)
