### ISSUE TITLE
yes build error

### ISSUE THREAD

**Issue by JazzMaster** [djm34/sgminer-msvc2015#2]
yes algo has build error but someone has src out here that builds. some of us cant use sgminer on ubu14/debian squeeze/fedora because of this.

      ^
algorithm/yescryptcommon.c:333:32: error: declaration for parameter ‘initialized’ but no such parameter
  static __declspec(thread) int initialized = 0;
                                ^
algorithm/yescryptcommon.c:361:1: error: expected ‘{’ at end of input
 }
 ^
algorithm/yescryptcommon.c: In function ‘yescrypt_bsty’:
algorithm/yescryptcommon.c:361:1: error: expected declaration or statement at end of input
make[2]: *** [algorithm/sgminer-yescryptcommon.o] Error 1
make[2]: Leaving directory `/home/me/Desktop/sgminer-l2z-src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/me/Desktop/sgminer-l2z-src'
make: *** [all] Error 2

and similar errors.

**Comment by djm34** [comment]
No build error :) 
This error has been corrected a week ago, please use the latest version from the master (not the release tar/gz) 
you should see that near the line 333 of yescryptcommon.c  (if itsn't the case, this isn't the latest version)
#ifdef _MSC_VER
	static __declspec(thread) int initialized = 0;
	static __declspec(thread)  yescrypt_shared_t shared;
	static __declspec(thread)  yescrypt_local_t local;
#else
	static __thread int initialized = 0;
	static __thread yescrypt_shared_t shared;
	static  __thread yescrypt_local_t local;
#endif
