### ISSUE TITLE
not working on windows 7

### ISSUE THREAD

**Issue by buzztiaan** [djm34/sgminer-msvc2015#3]
seems you linked to api-ms-win-core-libraryloader-l1-2-0.dll which doesnt exist for windows7 

could you maybe clear those linking , you should be using mincore.lib according to this;
https://answers.microsoft.com/en-us/windows/forum/windows_10-files/missing-api-ms-win-core-dlls/d99d1368-0f92-43db-bbdb-7d080f1f96e9

**Comment by djm34** [comment]
It is supposed to be a static build... 
I think it would probably be better to rebuilt it on win7.
anyhow, I added in the release, an exe built without mincore.lib (sgminer_nomincorelib.exe).

**Comment by buzztiaan** [comment]
Sadly nope, it still gives exact same error

**Comment by djm34** [comment]
9 days to give a feedback... hmm
well you need to recompile on win7

**Comment by buzztiaan** [comment]
i wasnt aware there was a limited timeframe for bugs to be retested? was this in README?

**Comment by klugev303** [comment]
have the same error on Windows 7 x64. What should we do? You will help?
