### ISSUE TITLE
SSLEAY32.dll and LIBEAY32.dll is missing

### ISSUE THREAD

**Issue by aaronsace** [djm34/sgminer-msvc2015#4]
Have you forgotten to include 'SSLEAY32.dll' and 'LIBEAY32.dll' in the new release? They were in the previous release.

**Comment by djm34** [comment]
It was compiled with their lib counterpart and they shouldn't be needed.
Does it work without or not ? (if not use the archive containing them)

**Comment by aaronsace** [comment]
It keeps popping up asking for them files then closes. Could you add the missing files to your release rar then it will work in MultiPoolMiner? (They were in your previous release. )

**Comment by kakadukaka** [comment]
Same here

**Comment by djm34** [comment]
New version of the binaries (sgminer.exe) in the release directory. 
Shouldn't complain about missing dll (this version uses 1.1.x branch of openssl).
The problem seen before was linked to curl libraries (which depends on openssl)

please let me know if the problem is now solved. 
Thanks.

**Comment by kakadukaka** [comment]
Thanx, all good

________________________________

**Comment by ericpolicastro** [comment]
DJM--

Can you please confirm my settings are correct. I have one RX480, OS is Linux 16.04 with GPUAMD-PRO driver, and I'm pulling about 500 kh/s...and getting crushed by everyone it seems. Would love to know I'm maximizing my hash or, if I'm not, what the heck I'm doing wrong.

export GPU_MAX_ALLOC_PERCENT=100
export GPU_USE_SYNC_OBJECTS=1
./sgminer -k lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:20581 -u eap50.34 -p x --xintensity 256 -w 32 --temp-cutoff 95 --auto-fan --gpu-memclock 2000 --gpu-engine 1170-1270 --shaders 2304 -g 2

**Comment by djm34** [comment]
ok thanks

**Comment by aaronsace** [comment]
The uploaded exe file doesn't include 'lyra2Z.cl'. 
Can you release it all together? 

> Unable to open lyra2Z.cl for reading!

**Comment by djm34** [comment]
It in is the directory "kernel" of the source
you should copy the entire directory "kernel" and put at the root of where you'll have the exe

**Comment by aaronsace** [comment]
I'm really just needing a single link to a working release that includes all the files like you did in the previous version so that it can be included with MultiPoolMiner.

**Comment by djm34** [comment]
you just have to look into the source here (github is more about source than exe) and pick up the kernel directory: 
https://github.com/djm34/sgminer-msvc2015/tree/master/kernel

**Comment by aaronsace** [comment]
Please can upload the release here: https://github.com/djm34/sgminer-msvc2015/releases

**Comment by aaronsace** [comment]
Can you upload a single working 'rar' file on the release page and I'll donate you some bitcoins?

**Comment by djm34** [comment]
I added the archive kernel.rar it needs to be used with the exe. but quite frankly you had already everything... as it is in the source

**Comment by aaronsace** [comment]
I don't think you understand; I simply mean a 'rar' file containing the exe and all the necessary files. 

Just like this one: https://github.com/djm34/sgminer-msvc2015/releases/download/v0.1-pre/sgminer-msvc2015.rar

You seem to be the only developer at the moment and would really appreciate it if you can upload a single link to the complete release.

**Comment by aaronsace** [comment]
Sorry, didn't mean to paste that ^^^

**Comment by djm34** [comment]
spoon feeding isn't much my stuff...

**Comment by aaronsace** [comment]
Ha, maybe I'm trying to spoon feed it to the masses with MultiPoolMiner. I'll transfer you 0.1 BTC if you upload a release rar. You are the only developer, I would really appreciate your support.

**Comment by aaronsace** [comment]
May we consider one another to provoke to love and to good works?

**Comment by djm34** [comment]
My address is here: 1NENYmxwZGHsKFmyjTc5WferTn5VTFb7Ze 
:) Thanks in advance

**Comment by aaronsace** [comment]
Are you uploading the one complete release rar file?

**Comment by ericpolicastro** [comment]
Shut the fuck up

On May 30, 2017 3:32 PM, "aaronsace" <notifications@github.com> wrote:

Can you upload a single working 'rar' file on the release page and I'll
donate you some bitcoins?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/djm34/sgminer-msvc2015/issues/4#issuecomment-304999310>,
or mute the thread

**Comment by aaronsace** [comment]
@ericpolicastro Hi?

Please don't post abusive messages on GitHub.

**Comment by djm34** [comment]
although, I do not condone the use of such language, it is true that it is the second time you make such promess and don't keep up to your word...

**Comment by aaronsace** [comment]
@djm34 Have you uploaded it? It's not showing when I look at it? 

I truly am trying to support this development; I hope there is no misunderstanding here. 

The 'exe' file is broken in the 'rar' file: https://github.com/djm34/sgminer-msvc2015/releases/download/v0.2-pre/sgminer-msvc2015.rar

Let me know when you've uploaded then I will send the Bitcoin :)

**Comment by djm34** [comment]
thanks in _advance_  ;)
(I mean, you made that request 23 days ago... and nothing happened since then ;)

**Comment by aaronsace** [comment]
@djm34 Sorry, I'm confused? 

Are my messages getting lost in translation? 
I don't understand?

**Comment by djm34** [comment]
I mean you make promesses, then you disapear entirely for a month and give no feedback on what got uploaded up to a month later because the archive isn't what you expected...

**Comment by aaronsace** [comment]
You should have explained earlier; this has been so complicated. **I'll transfer you now.** 

I develop MultiPoolMiner for www.miningpoolhub.com; you can see where I live online ;) I'm not going anywhere!

**Comment by aaronsace** [comment]
https://btc.blockr.io/tx/info/6ae2e71f54f30759f700f9cd3e7287d60875324a25bea8ba612d2a829e9fb009

Let me know when you have uploaded then I'll update the link in MultiPoolMiner. 

This is where your link will go once you have uploaded: https://github.com/aaronsace/MultiPoolMiner/blob/master/Miners/SgminerLyra2z.ps1

**Comment by djm34** [comment]
ok thanks a lot for the donation, I will do that at the earliest (most likely in the evening)

**Comment by djm34** [comment]
ok I have uploaded the kernel directory and binaries in a same archive. 
It can be found here: 
https://github.com/djm34/sgminer-msvc2015/releases/download/v0.2-pre/kernel_and_binary.rar
please report in case of problem

**Comment by aaronsace** [comment]
Perfect! Keep up the great work! :D
