### ISSUE TITLE
low hash rate with lyra2z?

### ISSUE THREAD

**Issue by eap50** [djm34/sgminer-msvc2015#5]
DJM--

Can you please confirm my settings are correct for mining with lyra2Z? I have one RX480 8GB, OS is Linux 16.04 with GPUAMD-PRO driver, and I'm pulling about 500 kh/s...and getting crushed by everyone it seems. Would love to know I'm maximizing my hash or, if I'm not, what the heck I'm doing wrong.

export GPU_MAX_ALLOC_PERCENT=100
export GPU_USE_SYNC_OBJECTS=1
./sgminer -k lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:20581 -u eap50.34 -p x --xintensity 256 -w 32 --temp-cutoff 95 --auto-fan --gpu-memclock 2000 --gpu-engine 1170-1270 --shaders 2304 -g 2

**Comment by djm34** [comment]
Hi, 
Please do not use github issue reporting system for asking question about how to use the miner.
This feature is only for reporting code issues and bugs. (you can contact me by other means such as slack, irc, etc...
