### ISSUE TITLE
missing api-ms-win-core-libraryloader-l1-2-0.dl

### ISSUE THREAD

**Issue by somidax** [djm34/sgminer-msvc2015#6]
Hi,

do anyone knows where i can get this missing file for sgminer
"api-ms-win-core-libraryloader-l1-2-0.dll "

"this will not allow the miner to start"

I will also suggest if this can be build into the miner so as it can run as stand alone. Appreciate your feedback ASAP

thanks!

**Comment by somidax** [comment]
pls note,
i have done this  https://answers.microsoft.com/en-us/windows/forum/windows_10-files/missing-api-ms-win-core-dlls/d99d1368-0f92-43db-bbdb-7d080f1f96e9?auth=1

and my rig is working fine 100%

**Comment by djm34** [comment]
is it working now ?

**Comment by somidax** [comment]
Ok will try it out and update ticket. But, should I download a fresh miner to rerun it on my rig?

Please advice.

Thanks!

**Comment by djm34** [comment]
? I don't know, you seemed to say in your second message that you solved the problem you described in the first message....
what OS are you working with ?
also a new bin has been uploaded a couple of day ago (did you use that one ?)

**Comment by somidax** [comment]
IN my second statement I mean to say I have scanned the system and notting
found missing.

Tested sgminer-GM "Lyra2v2" and it worked well but going back to use yours
for Lyra2z, same issue of missing dll.

My Os is win 7 x64 as your binary I am using is sgminer.exe file as well as
tested the previous record version and still same issue.

Please advice what should I do next.

Thanks!

**Comment by djm34** [comment]
sgminer-gm version is built with mingw (as far as I know), my version was built and developed around win10 with msvc2015. 
The link you quoted in your second message is also about win10, so I am not sure how you can have tested your system toward that...
I would suggest to move to win10 (or you can use the tar archive which contains already a bunch of dll files in the first release)
