### ISSUE TITLE
Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)

### ISSUE THREAD

**Issue by jjziets** [djm34/sgminer-msvc2015#7]
Not sure what I am doing wrong.
Running windows 10 64Bit
AMD driver 16.11.5
7 RX480
start command:
sgminer.exe --api-listen -k lyra2z -o stratum+ssl://europe.lyra2z-hub.miningpoolhub.com:17025 -u Etherion.ws10 -p x

![Uploading Capture.PNG…]()

**Comment by ericpolicastro** [comment]
Work size needs to be 32 or less

**Comment by jjziets** [comment]
Great thanks. that worked

**Comment by djm34** [comment]
that's the command line type you need to use: 

sgminer  --kernel lyra2Z   -o stratum+tcp://xzc.suprnova.cc:1598 -u djm34.1 -p password   -I 18 --worksize 32
