### ISSUE TITLE
minimum amd driver requirements? 

### ISSUE THREAD

**Issue by jjziets** [djm34/sgminer-msvc2015#8]
One of my mining rigs have old cards running amd 15.12 drivers. It is time to sell and upgrade I know but it is still make some profit.

I still get missing ssleay.dll and libssl.dll even with msvc2015. I have reinstalled your miner and the MSvc2015 64bit and 32bit. 

If i copy the ssleay.dll and libssl.dll in the same folder it crash

**Comment by jjziets** [comment]
I get this with v0.2-pre not with v0.1-pre.

**Comment by jjziets** [comment]
system is running windows 10 64bit.

**Comment by djm34** [comment]
the latest files I uploaded (see release content), doesn't require at all ssleay.dll libeay.dll (only the 64bit binaries were updated).

**Comment by ericpolicastro** [comment]
Ultimately (and unfortunately) my CPU miner is mining at 200% of the speed
of my gpu miner using Lyra2z. Sucks

On May 4, 2017 4:42 PM, "djm34" <notifications@github.com> wrote:

the latest files I uploaded (see release content), doesn't require at all
ssleay.dll libeay.dll

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/djm34/sgminer-msvc2015/issues/8#issuecomment-299317431>,
or mute the thread

**Comment by jjziets** [comment]
Nope. still happening. New rig with windows 10 64bit. using your sgminer-msvc2015 with command 
sgminer.exe --api-listen -k lyra2z --worksize 32 --intensity 13 -o stratum+ssl://europe.lyra2z-hub.miningpoolhub.com:17025 -u Etherion.wk1 -p x

got MSVC2015 installed. still gettting that ssleay.dll libeay.dll

rig is a 7 Asus RX480  4GB rig

**Comment by djm34** [comment]
are you using this one ? 
https://github.com/djm34/sgminer-msvc2015/releases/download/v0.2-pre/sgminer.exe
(I just tried on my pc and I don't have openssl installed and it doesn't give any error).
Actually this version isn't even compiled with the version which requires ssleay.dll, so I am a little surprised...
(this however hasn't been reflected to the source, I'll try to make an update a bit later)

**Comment by djm34** [comment]
check latest master this one should solve your problem. 
It also include lib and dll used (however it shouldn't as it is of the user responsability to include proper dependencies... however it must be noticed though that a compilation of libcurl is somewhat complicated and may cause problem. This should address those problem)

**Thanks for testing and reporting (especially as you opened the issue)**

**Comment by jjziets** [comment]
Ok so I downloaded the https://github.com/djm34/sgminer-msvc2015/releases/sgminer-msvc2015.rar

Extracted it to the correct folder and 

Then dl this https://github.com/djm34/sgminer-msvc2015/releases/download/v0.2-pre/sgminer.exe

Looks like it is working on all my windows 10  64 bit systems now. 


But on windows 7 64 bit I get 

![image](https://cloud.githubusercontent.com/assets/19214485/25945016/b3844960-3645-11e7-8c34-1ff11c8f7ac7.png)

**Comment by djm34** [comment]
try this: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

(it may or may not work... )

**Comment by jjziets** [comment]
IT is already installed it said. don't worry. all my main rigs run windows 10 anyway. just this one is on 7 due to driver/card issue.
