### ISSUE TITLE
Failed to run on Windows 8.1 x64

### ISSUE THREAD

**Issue by vzool** [djm34/sgminer-msvc2015#9]
Hi,

I'm trying to run this on Windows 8.1 x64 and I checked many binaries were available here, but no luck.

### Run test.bat
![zcoin-mining1](https://cloud.githubusercontent.com/assets/4952736/26751569/2a3d00ea-4845-11e7-88a7-f4ac1184f2c5.png)

### Here when I try to start mining using [sgminer_nomincorelib.exe](https://github.com/djm34/sgminer-msvc2015/releases/download/v0.2-pre/sgminer_nomincorelib.exe)

![zcoin-mining0](https://cloud.githubusercontent.com/assets/4952736/26751567/25305818-4845-11e7-85fb-2b4e78113201.png)

Do I miss something?

Thanks

**Comment by djm34** [comment]
These are due to missing dll, you probably need to use the archive with all the dll which are in the first release
you probably need to instal Visual C++ Redistributable for Visual Studio 2015 x64 (runtime libraries)
